# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-29 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=32, verbose_name=b'\xe5\x93\x81\xe7\x89\x8c')),
                ('model', models.CharField(max_length=32, verbose_name=b'\xe5\x9e\x8b\xe5\x8f\xb7')),
                ('number', models.CharField(max_length=32, verbose_name=b'\xe7\xbc\x96\xe5\x8f\xb7')),
                ('leader_time', models.DateTimeField(max_length=32, verbose_name=b'\xe9\xa2\x86\xe7\x94\xa8\xe6\x97\xb6\xe9\x97\xb4')),
                ('leader', models.CharField(max_length=32, verbose_name=b'\xe9\xa2\x86\xe7\x94\xa8\xe4\xba\xba')),
                ('return_time', models.DateTimeField(max_length=32, verbose_name=b'\xe5\xbd\x92\xe8\xbf\x98\xe6\x97\xb6\xe9\x97\xb4')),
                ('other', models.CharField(max_length=128, verbose_name=b'\xe5\xa4\x87\xe6\xb3\xa8')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('password', models.CharField(max_length=32, verbose_name=b'\xe5\xaf\x86\xe7\xa0\x81')),
                ('department', models.EmailField(max_length=32, verbose_name=b'\xe9\x83\xa8\xe9\x97\xa8')),
            ],
        ),
    ]
