# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.CharField(max_length=32, verbose_name=b'\xe9\x83\xa8\xe9\x97\xa8'),
        ),
    ]
