# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-01 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hnf', '0003_auto_20190401_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='return_time',
            field=models.DateTimeField(auto_now_add=True, max_length=32, null=True, verbose_name=b'\xe5\xbd\x92\xe8\xbf\x98\xe6\x97\xb6\xe9\x97\xb4'),
        ),
    ]
